# Generated by Django 2.1.2 on 2018-11-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('species_name', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('zh_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='pro_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_page.Protein'),
        ),
        migrations.AddField(
            model_name='animal',
            name='kind',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
